### ISSUE TITLE
您好，读了您的论文，有一些问题想问您？

### ISSUE THREAD

**Issue by yt-liang** [Jacob-Zhou/stack-parser#1]
您好，最近在学习您的《Is POS Tagging Necessary or Even Helpful for Neural Dependency》，代码地址显示的是您这里，但是目前还没有代码，冒昧的问您一下，代码之后会开放吗？如您能回复，不胜感激。

**Comment by Jacob-Zhou** [comment]
会的！我这两天整理一下代码。待弄好和您说一声吧



***@***.***
 
发件人： yt-liang
发送时间： 2021-04-10 16:35
收件人： Jacob-Zhou/stack-parser
抄送： Subscribed
主题： [Jacob-Zhou/stack-parser] 您好，读了您的论文，有一些问题想问您？ (#1)
您好，最近在学习您的《Is POS Tagging Necessary or Even Helpful for Neural Dependency》，代码地址显示的是您这里，但是目前还没有代码，冒昧的问您一下，代码之后会开放吗？如您能回复，不胜感激。

**Comment by Jacob-Zhou** [comment]
您好，代码已经更新！感谢您对我们工作的关注。

**Comment by yt-liang** [comment]
代码已经可以查看，再次感谢您。
